### ISSUE TITLE
Any plans for Kotlin <-> Swift?

### ISSUE THREAD

**Issue by alexandre-g** [angelolloqui/SwiftKotlin#1]
Hi there,

Are there any plans for implementing similar conversion the other way, from Kotlin to Swift?

If not, are you aware of any libraries like SwiftFormat for Kotlin or have any advice on how one would approach this task?

Thanks for the great work!

**Comment by angelolloqui** [comment]
It is not in the roadmap of this project, and I am not aware of anything like that at the moment. Doing the reverse would require to reimplement the tokenizer and rules, so that basically is duplicate most of the work.

**Comment by amorenew** [comment]
I wonder if you could fork https://github.com/moshbit/Kotlift 
and just add swift 3 support ? swift 2 already supported

**Comment by angelolloqui** [comment]
Sorry but Kotlift is an external project, I am not behind it. But I suggest you add the support yourself, I am sure they will welcome PRs
