### ISSUE TITLE
struct extends

### ISSUE THREAD

**Issue by llywuchen** [angelolloqui/SwiftKotlin#101]
struct User: Codable {
    var id: Int? = 0
    var name: String?
    var nick: String?
    var site: String?
}

into:

data class User: Codable(
    var id: Int? = 0,
    var name: String? = null,
    var nick: String? = null,
    var site: String? = null) {}

should be:

data class User(
    var id: Int? = 0,
    var name: String? = null,
    var nick: String? = null,
    var site: String? = null): Codable()

**Comment by angelolloqui** [comment]
Fixed with #107
