### ISSUE TITLE
Build failure with 0.25

### ISSUE THREAD

**Issue by graham-perks-snap** [angelolloqui/SwiftKotlin#119]
There's no sign of the UIKitTransformPlugin code, so Xcode gives this:

```
SwiftKotlin/Sources/SwiftKotlinApp/ViewController.swift:24:13: error: use of unresolved identifier 'UIKitTransformPlugin'
            UIKitTransformPlugin(),
            ^~~~~~~~~~~~~~~~~~~~

```

**Comment by graham-perks-snap** [comment]
```UIKitTransformPlugin```  doesn't seem to be part of the Xcode project.

**Comment by angelolloqui** [comment]
Have you run the installation steps?

```
swift package update
swift package generate-xcodeproj --enable-code-coverage
```

And are you using the workspace?

I have just downloaded the tag code and I got it running properly

**Comment by graham-perks-snap** [comment]
That was it.

All I did was a `git pull` for the update, at first. Thank you!
