### ISSUE TITLE
miss files

### ISSUE THREAD

**Issue by wz1383691** [angelolloqui/SwiftKotlin#12]
<unknown>:0: error: no such file or directory: '/Users/james/Desktop/download/SwiftKotlin-develop/Source/SwiftKotlinFramework/External/SwiftFormat/SwiftFormat/Tokenizer.swift'
<unknown>:0: error: no such file or directory: '/Users/james/Desktop/download/SwiftKotlin-develop/Source/SwiftKotlinFramework/External/SwiftFormat/SwiftFormat/Formatter.swift'

**Comment by angelolloqui** [comment]
Please, do the git submodule init as explained in the readme
