### ISSUE TITLE
No such module 'SwiftKotlinFramework'

### ISSUE THREAD

**Issue by Riuk005** [angelolloqui/SwiftKotlin#122]
I try to run the project and it's appear "No such module 'SwiftKotlinFramework'"

**Comment by angelolloqui** [comment]
Have you followed the installation instructions? In particular the Swift commands to generate the project?

**Comment by Riuk005** [comment]
I have problems with this... - Run swift package update and swift package generate-xcodeproj --enable-code-coverage

error: terminated(72): SHELL=/bin/bash LIBRARY_PATH=/usr/local/lib SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.5IymnAFi9V/Listeners XPC_FLAGS=0x0 __CF_USER_TEXT_ENCODING=0x1F5:0x0:0x8 TERM_PROGRAM_VERSION=433 CPATH=/usr/local/include PWD=/Users/name/Desktop/SwiftKotlin/SwiftKotlin XPC_SERVICE_NAME=0 TMPDIR=/var/folders/x3/dmxx40dj3_gbfwj9_d30jjzw0000gn/T/ TERM=xterm-256color TERM_SESSION_ID=0FE13179-5546-4031-9BFD-B4949AAB0781 _=/usr/bin/swift TERM_PROGRAM=Apple_Terminal USER=name SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin LOGNAME=name OLDPWD=/Users/name HOME=/Users/name SHLVL=1 LC_CTYPE=UTF-8 xcrun --sdk macosx --find xctest output:
    xcrun: error: unable to find utility "xctest", not a developer tool or in PATH

**Comment by Riuk005** [comment]
Sorry! I fix that... Now it's running!
