### ISSUE TITLE
unable to install SwiftKotlin

### ISSUE THREAD

**Issue by FabriceBali** [angelolloqui/SwiftKotlin#123]
hello, i've been trying to install your tool for quite a while, but can't. would you have a procedure for doing this, because the info in instal doesn't work for me. thank you in advance

**Comment by phyDevelop** [comment]
No need to install.
Download the latest from [releases](https://github.com/angelolloqui/SwiftKotlin/releases)
Open downloads -> SwiftKotlinApp 2020-05-17 18-12-47 -> Products -> Applications. Open SwiftKotlin.app as admin with rightClick and trust.
Insert text and read translation.

**Comment by angelolloqui** [comment]
Please provide the concrete steps you are doing and in which one (and with what error) fails for you. Remember to follow instructions as explained in the readme

**Comment by angelolloqui** [comment]
Closing due to 3 months of inactivity
