### ISSUE TITLE
Round the icon corners for Big Sur style

### ISSUE THREAD

**Issue by GeylanKalafMohe** [angelolloqui/SwiftKotlin#124]
the app icon is ugly please round the corners

**Comment by toshi0383** [comment]
@angelolloqui I'm currently learning design in my spare time. I can update app icon if you want.

**Comment by GeylanKalafMohe** [comment]
> @angelolloqui I'm currently learning design in my spare time. I can update app icon if you want.

Please do it and do a pull request
