### ISSUE TITLE
Add support for fatalError()

### ISSUE THREAD

**Issue by hlineholm** [angelolloqui/SwiftKotlin#14]
A fatal error in Swift 

`fatalError("An error \(error) occurred")` 

could be converted to 

`throw Exception("An error $error occurred")`

**Comment by angelolloqui** [comment]
Thanks. 

I think this will go when I make the Foundation converter plugin, in which I plan to replace things that are not part of the language itself but from the foundation types.

**Comment by angelolloqui** [comment]
Added a very simple version of this as part of 8b94a81d40d0b403d4095bc190cafe1e272ed96d
