### ISSUE TITLE
Add support for string interpolation

### ISSUE THREAD

**Issue by hlineholm** [angelolloqui/SwiftKotlin#15]
String interpolation in Swift 

`"An error \(error) occurred"` 

could be converted to 

`"An error $error occurred"`

**Comment by hlineholm** [comment]
I converted a file and the interpolation didn't work. Went through the source code and realised string interpolation should be working and retried converting my file, it suddenly worked.

**Comment by angelolloqui** [comment]
That is strange... I have never experienced anything like that... Could it be that the Swift code inside the expression (or around) was broken? do you have a reproduction scenario? It might be an issue detecting the expression from the AST parser.
