### ISSUE TITLE
Download page?

### ISSUE THREAD

**Issue by marchy** [angelolloqui/SwiftKotlin#3]
Hi there, you mention binaries are available for download on the info page but don't see any downloads enabled in GitHub. Mind please adding the release do that we don't have to build from sources for it?

Thx!

**Comment by angelolloqui** [comment]
Hi, 
Yes, sorry, I was waiting to have a stable build before publishing but I will consider to make one with the current preview state.

**Comment by Shahroz16** [comment]
Any update ? :/

**Comment by marchy** [comment]
I think preview would be fine, would still provide value to people converting things over even if it's not perfect / doesn't convert over everything. If you would have some time to post that would def be great.

**Comment by angelolloqui** [comment]
I have uploaded a non signed version of the Mac app here: https://github.com/angelolloqui/SwiftKotlin/releases/tag/0.0.1

Please, note that it is a very early release, still with many rules not implemented and some bugs.
