### ISSUE TITLE
Preserve original comments

### ISSUE THREAD

**Issue by angelolloqui** [angelolloqui/SwiftKotlin#36]
Current version transforms Swift code to an AST and then back to Kotlin, but the initial comments get removed. 

A possible solution would be to look for all comments (contained in the `TopDeclaration`) and look for the closest node in the Swift code and place it next to the first corresponding Kotlin token. This strategy could result in comments wrongly placed in some circumstances, but should work OK on most cases.

**Comment by prattcmp** [comment]
Id just like to add this could be super useful for iOS devs communicating code to Android devs.

**Comment by angelolloqui** [comment]
Merged with 73a4c529de6a00da8358c00087656bcbfd6fef74
