### ISSUE TITLE
typing double quotes into SwiftKotlin app becomes curly quotes

### ISSUE THREAD

**Issue by petermichaux** [angelolloqui/SwiftKotlin#46]
I tried typing the following into SwiftKotlin app. As I type it, the editor converts the first double quotation mark into curly quotes. Then the line cannot be translated because there is a parsing error.

```
let s: String = "abc"
```

If I copy and paste the above into SwiftKotlin app, the translation to Kotlin happens successfully.

**Comment by angelolloqui** [comment]
Thanks! Interesting that nobody reported this before. I guess the most common usage scenario is either copya&paste or open file, not typing directly. I will check it out

**Comment by angelolloqui** [comment]
Fixed with 5d1501293872493efcc075d58eabb8bea4c8ee71
