### ISSUE TITLE
conversion of lazy properties

### ISSUE THREAD

**Issue by petermichaux** [angelolloqui/SwiftKotlin#47]
This Swift

```
private lazy var name: String = {() -> String in
    return "abc"
}()
```

is translated to the following Kotlin

```
private lazy var name: String = {   -> 
    return "abc"
}()
```

I think it should result in the following Kotlin.

```
private val name: String by lazy {
    "abc"
}
```

The `var`, `val` issue is tricky. The `return` issue is tricky.

**Comment by angelolloqui** [comment]
Partially fixed with 972daf00dcbd5589ba3bc70065f81f3c90f779b9. However, the `return` statement is a different issue, related to how lambdas are translated (see #69)
