### ISSUE TITLE
get/set property in protocol

### ISSUE THREAD

**Issue by manuelgon47** [angelolloqui/SwiftKotlin#64]
Swift:
```
    var isPromotionLoading: Bool { get set }
```

Translated:
```
    var isPromotionLoading: Boolean {
        get
        set
    }
```

Correct translated
```
var isPromotionLoading: Boolean
```

**Comment by angelolloqui** [comment]
This actually works but you need to include the protocol definition. If you enter:
```
protocol A {
    var isPromotionLoading: Bool { get set }
}
```

then actual result is:
```
interface A {
    var isPromotionLoading: Boolean
}
```

Which is correct. And more over, if you remove the `set` from the definition, the resulting code will use `val` instead of `var`, so I think the funcitonality is OK.

Closing.
