### ISSUE TITLE
Kotlin -> Swift

### ISSUE THREAD

**Issue by giovannism20** [angelolloqui/SwiftKotlin#7]
If you can code in swift and go to kotlin, you can code in kotlin and go to swift ?

**Comment by gligorkot** [comment]
There is a library for that that I've found, not sure how good it is, and it also supports Kotlin 1.0.1 to Swift 2.2 conversion, so not going to be compatible with today's XCode given it's 2.2, but you can use the auto conversion of XCode after that I imagine and you would need to do some manual editing of the Swift code. The library is here:

https://github.com/moshbit/Kotlift

**Comment by angelolloqui** [comment]
Going from Kotlin to Swift would require a complete new set of tokenizer, rules and transformers. Not in the scope of this project. 
@gligorkot that looks like a very decent solution! I will add it to the readme
