### ISSUE TITLE
Undefined symbols error

### ISSUE THREAD

**Issue by alexyak** [angelolloqui/SwiftKotlin#72]
When I am trying to build the code in Xcode I get this:

Undefined symbols for architecture x86_64:
  "static (extension in Foundation):Swift.String._unconditionallyBridgeFromObjectiveC(__ObjC.NSString?) -> Swift.String", referenced from:
      __C.StringTransform.rawValue.getter : Swift.String in Attribute.o
      __C.StringTransform.rawValue.getter : Swift.String in Attributes.o
      __C.StringTransform.rawValue.getter : Swift.String in CodeBlock.o
      __C.StringTransform.rawValue.getter : Swift.String in GetterSetterBlock.o
      __C.StringTransform.rawValue.getter : Swift.String in GetterSetterKeywordBlock.o
      __C.StringTransform.rawValue.getter : Swift.String in WillSetDidSetBlock.o
      __C.StringTransform.rawValue.getter : Swift.String in ClassDeclaration.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
 
This happens when building AST.

**Comment by angelolloqui** [comment]
Can you please provide more information? 

At least:
- Xcode version
- Verify you have followed the steps in README
- Building steps followed (console or IDE?, what do you do,...)

**Comment by ghost** [comment]
I observe the same error. I'm using Xcode Version 9.3 (9E145), and follow the README steps exactly.
git clone ....
cd SwiftKotlin
swift package update
open SwiftKotlin.xcodeproj

click the build button to compile the Swift Kotlin package, and the error occurs.

I've tried compiling from both the master and develop branches. The result is the same in both cases

**Comment by angelolloqui** [comment]
Should be OK in #79 and #80
