### ISSUE TITLE
New released version doesn't work

### ISSUE THREAD

**Issue by andyrozman** [angelolloqui/SwiftKotlin#75]
Hi !
I downloaded last release and I tried to install it. UI Application works OK, but by running swift-transform I get weird error. Could you please package whole application? 

dyld: Library not loaded: @rpath/Transform.framework/Versions/A/Transform
  Referenced from: /usr/local/bin/swift-transform
  Reason: image not found
[1]    71712 abort      swift-transform

Any help will be appreciated.

Andy

**Comment by angelolloqui** [comment]
I have built the tool again: https://github.com/angelolloqui/SwiftKotlin/releases/download/0.1.4/swiftkotlin-CommandLine.zip

**Comment by goa** [comment]
Hi, I'm also getting this with the latest release, no matter how I try to build it.
