### ISSUE TITLE
update docs for gaurd clauses in kotlin

### ISSUE THREAD

**Issue by Groostav** [angelolloqui/SwiftKotlin#8]
you can replace

```kt
val data = someOptional
if(data == null) return
```

with

```kt
val data = someOptional ?: return
```

**Comment by Groostav** [comment]
So, I'll freely admit that I wrote this as a rabid kotlin fanboy without spending much time looking into source. And now that I see how much code is in this repo and your apparent understanding of kotlin, I feel like an idiot. 

so now I'll make a useful suggestion: It seems your doing everything at the text/token level. Have you considered perhaps trying to do this transformations at the AST level? [ANTLR now targets swift](https://github.com/antlr/antlr4/blob/master/doc/swift-target.md), and their [grammars repo has a swift g4 file](https://github.com/antlr/grammars-v4/tree/master/swift3), so it should be relatively simple to get ANTLR parsing swift. 

Once you've got that, and given that the general expression structure of swift and kotlin is so similar, it should be relatively simple to reduce your transforms to a reasonably small set of AST re-writes. Most of your rules could likely be broken down into a fairly simple "find subtrees matching this-shape and rewrite them to look like this".

Given these things, the implementation would look like this:

```kt
//note I'm writing in kotlin because I dont know swift :P

override fun exitGuard_Statement(ctx: Guard_statementContext){
  //note the grammar uses snake-cases, which is a tad unconventional 
  //and results in the odd class name "Guard_statementContext"

  val childReturnStatement = node.child<Code_BlockContext>()?.cast<Return_statementContext>() ?: return;
  if(/*additional checks against return statement if necessary?*/) return

  //perform tree re-write. some notes:
  // if this is being used as part of a fixed point strategy, then we need to signal that this method made a change
  // it is important that we perform this re-write on the exit (post-order) portion of the traversal,
  // else we risk modifying a tree that we're in the process of iterating through.

  val replacement = Constant_declarationContext(
      attributes = emptyList(), 
      declaration_modifiers = emptyList(),
      initializer = listOf(KotlinElvisGeneratedContext(ctx.condition_list, ctx.code_block))
  )
  ctx.parent.replace(ctx, replacement)

}

class KotlinElvisGeneratedContext(val left: RuleContext, val right: RuleContext)
```

**Comment by angelolloqui** [comment]
yes, I actually started with an AST tree based on SourceKit (and I also checked antlr with the swift grammar rule) but in my initial attempts everything looked much more difficult and longer in terms of effort, especially given the similarity of Swift and Kotlin. For that reason, I decided to restart with a simple tokenizer, but if you think the AST will be simpler please go ahead, I will be happy to help migrating the existing rules to the new AST.

**Comment by angelolloqui** [comment]
I am closing this issue for now. In parallel, I am exploring different AST libraries, trying to find one that allows the extra power without the hazzle. I will probably post news in about 1 month about this.

**Comment by angelolloqui** [comment]
A working AST version can be found on https://github.com/angelolloqui/SwiftKotlin/tree/feature/swift-transform
