### ISSUE TITLE
Dealing with localisation

### ISSUE THREAD

**Issue by MFJones21** [angelolloqui/SwiftKotlin#98]
Hi ! I found this awesome software and want to translate some code I wrote to use it in Java. How do I deal with the **NSLocalizedString**s that I used in my swift code ? Thanks for the Help in advance.

**Comment by angelolloqui** [comment]
Hi,
`NSLocalizedString` is a framework utility in the same way than others like `UIView` or `CGSize`, not a language feature. As such, there is no plan to convert that code and you will have to find a way to translate it on your own. Remember that this project’s aim is to convert Swift to Kotlin on syntactic level, not to fully replicate all framework features from the first to the latter.

That being said, I would make some changes to your code. For example, if you use it to port iOS to Android, you could start by replacing your strings iOS code by something more robust like [R.swift](https://github.com/mac-cain13/R.swift) that will not only improve your iOS code quality but also make it trivial to port the code to Android as it follows almost identical name conventions.

**Comment by MFJones21** [comment]
Thank you for your swift answer. Could you give ma a hint on how to translate these (CGSize, CGPoint etc.)? A hint would also be fine aswell =)
