### ISSUE TITLE
Commandline run error

### ISSUE THREAD

**Issue by mortenholmgaard** [angelolloqui/SwiftKotlin#99]
I have tried to run two latest release versions from the commandline but I keep getting this error when i run `swiftkotlin`:
```
dyld: Symbol not found: _$SBOWV
 Referenced from: /usr/local/bin/Bocho.framework/Versions/A/Bocho
 Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib
in /usr/local/bin/Bocho.framework/Versions/A/Bocho
Abort trap: 6
```

I have copied all the files from `SwiftKotlinCommandLine*.xarchive/Products/usr/local/bin/` to `~/usr/local/bin`
The Application runs just fine.

What am I doing wrong?

**Comment by mortenholmgaard** [comment]
@angelolloqui Any clue what the problem is?

**Comment by angelolloqui** [comment]
Hi, I haven't checked the problem but I guess the export process has gone wrong. I suggest you build it yourself or use the desktop app as a temporal fix until I make a new export of the console utility

**Comment by antygravity** [comment]
Here is a solution https://stackoverflow.com/a/56289004/5612090

**Comment by mortenholmgaard** [comment]
We have got I working by compiling it our self. But the output path parameter didn't seem to work when using it on a directory.

**Comment by angelolloqui** [comment]
Closing due to age. If problem still persists on next release, please open a new one with the steps and errors
